controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
register:
    path: /registration
    controller: App\Controller\RegistrationController::index
list:
    path: /list
    controller: App\Controller\ListController::createList
login:
    path: /
    controller: App\Controller\SecurityController::login
profile:
    path: '/profile'
    controller: 'App\Controller\ProfileController::index'
list_type:
    path: /list/type/
    controller: App\Controller\ListTypeController::index
app_access_denied:
    path: /access-denied
    controller: App\Controller\AccessDeniedController::index
app_forgot_password_request:
    path: '/forgot-password'
    controller: App\Controller\SecurityController::forgotPasswordRequest
    methods: ['GET', 'POST']
app_forgot_password_check:
    path: '/forgot-password/check'
    controller: App\Controller\SecurityController::forgotPasswordCheck
    methods: ['GET', 'POST']
rest:
    path: '/forgot-password/rest'
    controller: App\Controller\SecurityController::rest
    methods: ['GET', 'POST']
